#!/usr/bin/env python3
"""
Assembles LGAM subpages from shared partials + per-page content.
Run from anywhere: python gds-local/_build/build.py

Zero external dependencies — uses only Python stdlib.

Page statuses (for built pages in _pages/):
  - published: built to root (live) AND preview/. Linked from index.
  - draft:     built to preview/ only. Not linked from index.
  - modified:  built to preview/ only (root keeps last-published version). Linked from index.

Hand-authored pages (index.html, gds-local-alt.html):
  - Root file = published version (edit directly to publish)
  - If a working copy exists in _build/_hand/, it is used for preview/ instead
  - This allows unapproved changes to be previewed without affecting the live site
"""

import os
import re
import shutil
import sys
import datetime
import subprocess

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
GDS_LOCAL_DIR = os.path.dirname(SCRIPT_DIR)
PARTIALS_DIR = os.path.join(SCRIPT_DIR, "_partials")
PAGES_DIR = os.path.join(SCRIPT_DIR, "_pages")
HAND_DIR = os.path.join(SCRIPT_DIR, "_hand")
PREVIEW_DIR = os.path.join(GDS_LOCAL_DIR, "preview")

# Hand-authored files to include in preview
HAND_AUTHORED_FILES = ["index.html", "gds-local-alt.html"]

GENERATED_COMMENT = "<!-- Generated by build.py — do not edit directly -->\n"


def read_partial(name):
    with open(os.path.join(PARTIALS_DIR, name), "r", encoding="utf-8") as f:
        return f.read()


def parse_page(filepath):
    """Parse a page source file into front matter dict and content blocks."""
    with open(filepath, "r", encoding="utf-8") as f:
        raw = f.read()

    # Parse front matter
    if not raw.startswith("---"):
        raise ValueError(f"{filepath}: missing front matter (must start with ---)")

    end = raw.index("---", 3)
    fm_block = raw[3:end].strip()
    body = raw[end + 3:].strip()

    front_matter = {}
    for line in fm_block.splitlines():
        if ":" in line:
            key, val = line.split(":", 1)
            front_matter[key.strip()] = val.strip().strip('"').strip("'")

    # Extract tagged blocks
    def extract_block(tag):
        pattern = f"<{tag}>(.*?)</{tag}>"
        m = re.search(pattern, body, re.DOTALL)
        return m.group(1) if m else ""

    blocks = {
        "style": extract_block("style"),
        "nav_contents": extract_block("nav-contents"),
        "main_content": extract_block("main-content"),
        "page_script": extract_block("page-script"),
        "page_modules": extract_block("page-modules"),
        "page_history": extract_block("page-history"),
    }

    return front_matter, blocks


def build_page(target_filename, front_matter, blocks, is_preview=False):
    """Assemble a full HTML page from partials and page-specific blocks."""
    head_open = read_partial("head-open.html")
    header = read_partial("header.html")
    sidebar_lgam = read_partial("sidebar-lgam.html")
    footer = read_partial("footer.html")

    # Replace template variables in head
    title = front_matter.get("title", "Page")
    head_open = head_open.replace("{{ title }}", title)

    # Parent page support
    parent = front_matter.get("parent", "")
    parent_title = front_matter.get("parent_title", "")

    # Calculate depth to fix relative links to the root index.html
    depth = target_filename.count("/")
    if is_preview:
        depth += 1
    prefix = "../" * depth
    head_open = head_open.replace("{{ prefix }}", prefix)
    footer = footer.replace("{{ prefix }}", prefix)

    if depth > 0:
        header = header.replace('href="index.html"', f'href="{prefix}index.html"')
        sidebar_lgam = sidebar_lgam.replace('href="index.html"', f'href="{prefix}index.html"')
        sidebar_lgam = sidebar_lgam.replace('href="index.html#', f'href="{prefix}index.html#')

    # Assemble
    parts = []
    parts.append(GENERATED_COMMENT)
    parts.append(head_open)

    # Page-specific CSS
    if blocks["style"].strip():
        parts.append("\n  <style>\n")
        parts.append(blocks["style"])
        parts.append("\n  </style>\n")

    parts.append("</head>\n\n")

    # Body: header + service nav + phase banner
    parts.append(header)

    layout = front_matter.get("layout", "default")

    # Service nav with feedback link
    parts.append(f"""
  <nav class="app-service-nav" aria-label="Service">
    <div class="govuk-width-container">
      <ul class="app-service-nav__list">
        <li><a class="app-service-nav__link" href="{prefix}index.html">Documentation</a></li>
        <li><a class="app-service-nav__link" href="mailto:gdslocal-info@dsit.gov.uk">Contact GDS Local</a></li>
        <li><a class="app-service-nav__link" href="mailto:gdslocal-info@dsit.gov.uk?subject=LGAM%20Feedback" data-feedback-trigger="usage">Give feedback</a></li>
      </ul>
    </div>
  </nav>
""")

    if layout == "full-width":
        parts.append("  <div class=\"app-content-wrapper app-content-wrapper--full-width\">\n")
        parts.append("      <main class=\"app-main-content app-main-content--full-width\" id=\"main-content\" role=\"main\">\n")
        parts.append(blocks["main_content"])
    else:
        # Content wrapper with sidebar + main
        parts.append("  <div class=\"app-content-wrapper\">\n")
        parts.append("    <nav class=\"app-sidebar\" aria-label=\"Page navigation\">\n")

        # Back-link for child pages
        if parent:
            back_text = f"Back to {parent_title}" if parent_title else "Back"
            parts.append(f"      <a href=\"{parent}\" class=\"govuk-back-link govuk-!-margin-bottom-4 govuk-!-margin-top-0\">{back_text}</a>\n")

        parts.append("      <h2 class=\"app-navigation__heading\">Contents</h2>\n")
        parts.append("      <ul class=\"app-navigation\">\n")
        parts.append(blocks["nav_contents"])
        parts.append("\n      </ul>\n")

        parts.append(sidebar_lgam)

        parts.append("    </nav>\n\n")
        parts.append("      <main class=\"app-main-content\" id=\"main-content\" role=\"main\">\n")
        parts.append(blocks["main_content"])

    if blocks.get("page_history", "").strip():
        parts.append("\n<hr class=\"govuk-section-break govuk-section-break--xl govuk-section-break--visible\">\n")
        parts.append("<details class=\"govuk-details\" data-module=\"govuk-details\">\n")
        parts.append("  <summary class=\"govuk-details__summary\">\n")
        parts.append("    <span class=\"govuk-details__summary-text\">Page history</span>\n")
        parts.append("  </summary>\n")
        parts.append("  <div class=\"govuk-details__text\">\n")
        parts.append("    " + blocks["page_history"].strip().replace("\n", "\n    ") + "\n")
        parts.append("  </div>\n")
        parts.append("</details>\n")

    # Per-page feedback link
    encoded_title = title.replace(" ", "%20").replace("&", "%26")
    parts.append(f"""
        <hr class="govuk-section-break govuk-section-break--l govuk-section-break--visible">
        <p class="govuk-body-s" style="color:#505a5f;">
          Help improve this page —
          <a class="govuk-link" href="mailto:gdslocal-info@dsit.gov.uk?subject=LGAM%20feedback:%20{encoded_title}" data-feedback-trigger="page" data-feedback-page="{title}">suggest a change</a>
        </p>
""")

    parts.append("\n      </main>\n")
    parts.append("  </div>\n\n")

    # Footer
    parts.append(footer)

    # Page-specific script
    if blocks["page_script"].strip():
        parts.append("\n  <script>\n")
        parts.append(blocks["page_script"])
        parts.append("\n  </script>\n")

    # Optional shared script modules
    modules = blocks.get("page_modules", "").strip()
    if modules:
        for module in modules.split(","):
            module = module.strip()
            partial_name = f"script-{module}.html"
            partial_path = os.path.join(PARTIALS_DIR, partial_name)
            if os.path.exists(partial_path):
                parts.append("\n  <script>\n")
                parts.append(read_partial(partial_name))
                parts.append("\n  </script>\n")

    # Feedback modal dialog (progressive enhancement)
    parts.append("""
  <dialog id="lgam-feedback-dialog" class="lgam-feedback-dialog" aria-labelledby="feedback-modal-title" aria-modal="true">
    <div class="lgam-feedback-dialog__header">
      <h2 class="govuk-heading-m govuk-!-margin-bottom-0" id="feedback-modal-title"></h2>
      <button type="button" class="lgam-feedback-dialog__close" id="feedback-modal-close" aria-label="Close">&#215;</button>
    </div>
    <div class="lgam-feedback-dialog__body" id="feedback-modal-body"></div>
    <div class="lgam-feedback-dialog__footer">
      <div class="feedback-footer-info">
        <p class="govuk-body-s govuk-!-margin-bottom-0" id="feedback-aggregate-count" aria-live="polite" aria-atomic="true"></p>
        <p class="govuk-body-s govuk-!-margin-bottom-0" style="color:#505a5f;">This will open a pre-filled email in your email client.</p>
      </div>
      <div class="feedback-footer-actions">
        <button type="button" class="govuk-button govuk-button--secondary govuk-!-margin-bottom-0" id="feedback-modal-cancel">Cancel</button>
        <button type="button" class="govuk-button govuk-!-margin-bottom-0" id="feedback-modal-submit">Open in email</button>
      </div>
    </div>
  </dialog>
""")
    parts.append(f'  <script src="{prefix}js/feedback-modal.js"></script>\n')

    parts.append("</body>\n</html>\n")

    return "".join(parts)


def update_index_links(pages):
    """Insert/remove 'View X detail' links in index.html based on page status."""
    index_path = os.path.join(GDS_LOCAL_DIR, "index.html")
    if not os.path.exists(index_path):
        print("  [skip] index.html not found")
        return

    with open(index_path, "r", encoding="utf-8") as f:
        html = f.read()

    original = html

    for filename, fm in pages:
        index_title = fm.get("index_title", fm.get("title", ""))
        status = fm.get("status", "draft")
        target = fm.get("target", filename)
        
        if not index_title:
            continue

        link_url = target if status in ("published", "modified") else filename

        # Build the link paragraph we want to insert/find
        link_para = (
            f'<p class="govuk-body govuk-!-margin-top-3 govuk-!-margin-bottom-0">'
            f'<a href="{link_url}" class="govuk-link">View {fm.get("title", "")} detail&nbsp;&rarr;</a></p>'
        )

        # Pattern to find existing auto-generated link for this file or target
        link_pattern = re.compile(
            r'<p class="govuk-body govuk-!-margin-top-3 govuk-!-margin-bottom-0">'
            r'<a href="(?:' + re.escape(filename) + r'|' + re.escape(target) + r')"[^>]*>View [^<]+ detail[^<]*</a></p>\n?'
        )

        # Find the item whose summary text matches the index_title (case-insensitive)
        summary_pattern = re.compile(
            r'(<details[^>]*>.*?<summary[^>]*>\s*<span[^>]*>)\s*'
            + re.escape(index_title)
            + r'\s*(</span>\s*</summary>.*?<div class="govuk-details__text">)(.*?)(</div>\s*</details>)',
            re.DOTALL | re.IGNORECASE,
        )

        match = summary_pattern.search(html)
        if not match:
            continue

        details_text = match.group(3)

        if status in ("published", "modified"):
            if link_pattern.search(details_text):
                continue
            first_p_end = re.search(r'</p>', details_text)
            if first_p_end:
                insert_pos = match.start(3) + first_p_end.end()
                html = html[:insert_pos] + "\n                    " + link_para + html[insert_pos:]
        else:
            html = link_pattern.sub("", html)

    if html != original:
        with open(index_path, "w", encoding="utf-8") as f:
            f.write(html)
        print("  [updated] index.html")
    else:
        print("  [unchanged] index.html")


def _folder_label(folder_name):
    """Derive a human-readable label from a folder name."""
    return folder_name.replace("-", " ").title()


def generate_preview_index(pages_meta):
    """Generate a hierarchically grouped preview index page."""
    from collections import OrderedDict

    tag_colours = {"published": "green", "draft": "grey", "modified": "yellow"}

    # Build a two-level hierarchy: top_folder → sub_folder → [(filename, fm)]
    # For single-depth folders (e.g. integration/index.html) sub_folder is ""
    # For root pages (e.g. payments.html) top_folder is ""
    hierarchy = OrderedDict()
    for filename, fm in pages_meta:
        parts = filename.split("/")
        if len(parts) == 1:
            top, sub, concept = "", "", ""
        elif len(parts) == 2:
            top, sub, concept = parts[0], "", ""
        elif len(parts) == 3:
            top, sub, concept = parts[0], parts[1], ""
        else:
            top, sub, concept = parts[0], parts[1], parts[2]
        hierarchy.setdefault(top, OrderedDict()).setdefault(sub, OrderedDict()).setdefault(concept, []).append((filename, fm))

    def _render_page_table(pages, lines):
        """Render a GOV.UK table for a list of pages."""
        lines.append('<table class="govuk-table">')
        lines.append('<thead class="govuk-table__header"><tr>')
        lines.append('<th class="govuk-table__header" style="width:30%">Page</th>')
        lines.append('<th class="govuk-table__header" style="width:15%">Status</th>')
        lines.append('<th class="govuk-table__header" style="width:15%">Last updated</th>')
        lines.append('<th class="govuk-table__header" style="width:40%">Description</th>')
        lines.append("</tr></thead>")
        lines.append('<tbody class="govuk-table__body">')

        for filename, fm in pages:
            title = fm.get("title", filename)
            status = fm.get("status", "draft")
            colour = tag_colours.get(status, "grey")
            description = fm.get("description", "")
            caption = fm.get("caption", "")
            display_name = os.path.basename(filename)

            # Get last modified date from file
            filepath = os.path.join(PAGES_DIR, filename)
            mtime = os.path.getmtime(filepath)
            last_modified = datetime.datetime.fromtimestamp(mtime).strftime("%d %b %Y")

            lines.append('<tr class="govuk-table__row">')
            lines.append(f'<td class="govuk-table__cell"><a class="govuk-link" href="{filename}">{title}</a>'
                         f'<br><span class="directory-page-name">{display_name}</span></td>')
            lines.append(f'<td class="govuk-table__cell"><strong class="govuk-tag govuk-tag--{colour}">{status}</strong></td>')
            lines.append(f'<td class="govuk-table__cell"><span class="directory-desc">{last_modified}</span></td>')
            desc_text = description if description else f'<span class="directory-desc">{caption}</span>' if caption else ""
            lines.append(f'<td class="govuk-table__cell">{desc_text}</td>')
            lines.append("</tr>")

        lines.append("</tbody></table>")
    # Top-level folder colors for LGAM
    lgam_colors = {
        "public-channels": "#CC00CC",
        "council-interfaces": "#800080",
        "capabilities": "#000080",
        "business-area": "#0000FF",
        "corporate-areas": "#696969",
        "foundational-technology": "#008080",
        "integration": "#6B6B00",
        "security": "#CC0000",
        "data-and-information": "#800000",
        "topics": "#626a6e"
    }

    # --- Build the HTML ---
    lines = []
    lines.append("<!DOCTYPE html>")
    lines.append('<html lang="en"><head>')
    lines.append('<meta charset="utf-8">')
    lines.append('<title>LGAM Preview Index</title>')
    lines.append('<meta name="viewport" content="width=device-width, initial-scale=1">')
    lines.append('<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/govuk-frontend@5.13.0/dist/govuk/govuk-frontend.min.css">')
    lines.append('<style>')
    lines.append('  .directory-desc { color: #505a5f; font-size: 16px; }')
    lines.append('  .directory-section { margin-bottom: 40px; padding: 20px; background: #f3f2f1; border-left: 10px solid #b1b4b6; }')
    lines.append('  .directory-subsection { margin-top: 20px; }')
    lines.append('  .directory-page-name { font-family: monospace; font-size: 14px; color: #505a5f; }')
    lines.append('  .govuk-details { background: #fff; padding: 15px; border: 1px solid #b1b4b6; }')
    lines.append('</style>')
    lines.append('</head><body class="govuk-template__body">')
    lines.append('<script type="module" src="https://cdn.jsdelivr.net/npm/govuk-frontend@5.13.0/dist/govuk/govuk-frontend.min.js"></script>')
    lines.append('<script type="module">import { initAll } from "https://cdn.jsdelivr.net/npm/govuk-frontend@5.13.0/dist/govuk/govuk-frontend.min.js"; initAll();</script>')
    lines.append('<div class="govuk-width-container" style="max-width: 90%; padding: 30px 0;">')
    lines.append('<h1 class="govuk-heading-l">LGAM Preview Pages</h1>')
    lines.append('<p class="govuk-body">These pages are drafts or have unapproved modifications. They are not linked from the live site.</p>')

    # Hand-authored pages
    lines.append('<div class="directory-section" style="border-left-color: #0b0c0c;">')
    lines.append('<h2 class="govuk-heading-m">Hand-authored pages</h2>')
    lines.append('<ul class="govuk-list govuk-list--bullet">')
    for filename in HAND_AUTHORED_FILES:
        preview_path = os.path.join(PREVIEW_DIR, filename)
        if os.path.exists(preview_path):
            hand_path = os.path.join(HAND_DIR, filename)
            state = "modified" if os.path.exists(hand_path) else "published"
            lines.append(f'<li><a class="govuk-link" href="{filename}">{filename}</a> <strong class="govuk-tag govuk-tag--{"yellow" if state == "modified" else "green"}">{state}</strong></li>')
    lines.append("</ul>")
    lines.append("</div>")

    # Built pages, grouped hierarchically
    for top_folder, sub_groups in hierarchy.items():
        top_label = _folder_label(top_folder) if top_folder else "General"
        has_sub_sections = any(sub for sub in sub_groups.keys() if sub)
        color = lgam_colors.get(top_folder, "#b1b4b6")

        lines.append(f'<div class="directory-section" style="border-left-color: {color};">')
        lines.append(f'<details class="govuk-details" data-module="govuk-details" open>')
        lines.append(f'<summary class="govuk-details__summary"><span class="govuk-details__summary-text govuk-heading-m govuk-!-margin-bottom-0">{top_label}</span></summary>')
        lines.append('<div class="govuk-details__text govuk-!-padding-top-4">')

        if has_sub_sections:
            for sub_folder, concept_groups in sub_groups.items():
                if sub_folder:
                    sub_label = _folder_label(sub_folder)
                    lines.append('<div class="directory-subsection">')
                    lines.append('<details class="govuk-details" data-module="govuk-details">')
                    lines.append(f'<summary class="govuk-details__summary"><span class="govuk-details__summary-text govuk-heading-s govuk-!-margin-bottom-0">{sub_label}</span></summary>')
                    lines.append('<div class="govuk-details__text govuk-!-padding-top-2">')
                    
                    has_concepts = any(c for c in concept_groups.keys() if c)
                    if has_concepts:
                        for concept_folder, pages in concept_groups.items():
                            if concept_folder:
                                concept_label = _folder_label(concept_folder)
                                lines.append('<div class="directory-subsection">')
                                lines.append('<details class="govuk-details" data-module="govuk-details">')
                                lines.append(f'<summary class="govuk-details__summary"><span class="govuk-details__summary-text govuk-!-margin-bottom-0" style="font-weight:bold;">{concept_label}</span></summary>')
                                lines.append('<div class="govuk-details__text govuk-!-padding-top-2">')
                                _render_page_table(pages, lines)
                                lines.append("</div></details></div>")
                            else:
                                _render_page_table(pages, lines)
                    else:
                        all_pages = []
                        for pages in concept_groups.values():
                            all_pages.extend(pages)
                        _render_page_table(all_pages, lines)
                        
                    lines.append("</div></details></div>")
                else:
                    # Pages directly under the top folder (no sub-folder)
                    all_pages = []
                    for pages in concept_groups.values():
                        all_pages.extend(pages)
                    _render_page_table(all_pages, lines)
        else:
            # Flat section — all pages are directly under this folder
            all_pages = []
            for concept_groups in sub_groups.values():
                for pages in concept_groups.values():
                    all_pages.extend(pages)
            _render_page_table(all_pages, lines)

        lines.append("</div></details></div>")

    lines.append("</div></body></html>")

    index_path = os.path.join(PREVIEW_DIR, "directory.html")
    with open(index_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"\n  Preview index: preview/directory.html")


def main():
    os.chdir(GDS_LOCAL_DIR)

    print("Running asset pipeline...")
    # 1. Compile SCSS to CSS
    try:
        subprocess.run(["npx", "sass", "--load-path=.", "src/scss/application.scss", "css/application.css"], check=True)
        print("  [success] Compiled src/scss/application.scss -> css/application.css")
    except subprocess.CalledProcessError as e:
        print("  [error] SCSS compilation failed. Ensure Dart Sass is installed.")
        sys.exit(1)

    # 2. Copy the UMD JS bundle from node_modules
    os.makedirs("js", exist_ok=True)
    bundle_src = "node_modules/govuk-frontend/dist/govuk/all.bundle.js"
    if os.path.exists(bundle_src):
        shutil.copy2(bundle_src, "js/govuk-frontend.min.js")
        print("  [success] Copied all.bundle.js -> js/govuk-frontend.min.js")
    else:
        print("  [warning] all.bundle.js not found in node_modules! Run `npm install`.")

    if not os.path.isdir(PAGES_DIR):
        print(f"Error: pages directory not found: {PAGES_DIR}", file=sys.stderr)
        sys.exit(1)

    page_files = []
    for root_dir, _, files in os.walk(PAGES_DIR):
        for f in files:
            if f.endswith(".html"):
                rel_path = os.path.relpath(os.path.join(root_dir, f), PAGES_DIR)
                page_files.append(rel_path)
    page_files = sorted(page_files)

    if not page_files:
        print("No page sources found in _pages/")
        return

    # Ensure preview directory exists
    os.makedirs(PREVIEW_DIR, exist_ok=True)

    print(f"Building {len(page_files)} page(s)...\n")

    pages_meta = []

    published_targets = {}
    
    for filename in page_files:
        filepath = os.path.join(PAGES_DIR, filename)
        fm, blocks = parse_page(filepath)
        status = fm.get("status", "draft")
        target = fm.get("target", filename)

        # Build preview using original filename (preserves source tree structure in preview)
        preview_output = build_page(filename, fm, blocks, is_preview=True)
        preview_path = os.path.join(PREVIEW_DIR, filename)
        os.makedirs(os.path.dirname(preview_path), exist_ok=True)
        with open(preview_path, "w", encoding="utf-8") as f:
            f.write(preview_output)

        # Only write to root for published pages
        root_path = os.path.join(GDS_LOCAL_DIR, target)
        if status == "published":
            # If target depth differs, re-render to get correct relative prefixes
            if target.count("/") != filename.count("/"):
                published_output = build_page(target, fm, blocks)
            else:
                published_output = preview_output
                
            # Collision detection
            if target in published_targets:
                print(f"\nERROR: Multiple published files target '{target}': {published_targets[target]} and {filename}", file=sys.stderr)
                sys.exit(1)
            published_targets[target] = filename

            os.makedirs(os.path.dirname(root_path), exist_ok=True)
            with open(root_path, "w", encoding="utf-8") as f:
                f.write(published_output)
                
            if target != filename:
                print(f"  [published]  {filename} -> {target}")
            else:
                print(f"  [published]  {filename}")
        elif status == "modified":
            print(f"  [modified]   {filename} (preview only, root unchanged)")
        else:
            print(f"  [draft]      {filename} (preview only)")

        # Generate redirects if specified in front matter
        redirect_from = fm.get("redirect_from", "")
        if redirect_from:
            for old_path in [p.strip() for p in redirect_from.split(",") if p.strip()]:
                rel_url = os.path.relpath(filename, os.path.dirname(old_path) or ".")
                redirect_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Redirecting&hellip;</title>
    <link rel="canonical" href="{rel_url}">
    <script>location="{rel_url}"</script>
    <meta http-equiv="refresh" content="0; url={rel_url}">
    <meta name="robots" content="noindex">
</head>
<body>
    <h1>Redirecting&hellip;</h1>
    <a href="{rel_url}">Click here if you are not redirected.</a>
</body>
</html>"""
                old_preview = os.path.join(PREVIEW_DIR, old_path)
                os.makedirs(os.path.dirname(old_preview), exist_ok=True)
                with open(old_preview, "w", encoding="utf-8") as f:
                    f.write(redirect_html)
                if status == "published":
                    old_root = os.path.join(GDS_LOCAL_DIR, old_path)
                    os.makedirs(os.path.dirname(old_root), exist_ok=True)
                    with open(old_root, "w", encoding="utf-8") as f:
                        f.write(redirect_html)

        pages_meta.append((filename, fm))

    # Update index.html links (published + modified get links, draft doesn't)
    print("\nUpdating index.html links...")
    update_index_links(pages_meta)

    # Handle hand-authored files for preview
    print("\nHand-authored pages:")
    for filename in HAND_AUTHORED_FILES:
        hand_path = os.path.join(HAND_DIR, filename)
        root_path = os.path.join(GDS_LOCAL_DIR, filename)
        preview_path = os.path.join(PREVIEW_DIR, filename)

        if os.path.exists(hand_path):
            # Working copy exists — use it for preview (root stays as published)
            shutil.copy2(hand_path, preview_path)
            print(f"  [modified]   {filename} (preview from _hand/, root unchanged)")
        elif os.path.exists(root_path):
            # No working copy — root IS the current version, copy to preview
            shutil.copy2(root_path, preview_path)
            print(f"  [published]  {filename} (copied to preview)")
        else:
            print(f"  [skip]       {filename} (not found)")

    # Generate preview link index
    generate_preview_index(pages_meta)

    print(f"\nPreview: {PREVIEW_DIR}/")
    print("Done.")


if __name__ == "__main__":
    main()
